"""Tests for the PasswordHasher class."""
import pytest

from src.platform.security.password import PasswordHasher


class TestPasswordHasher:
    """Tests for PasswordHasher."""

    @pytest.fixture
    def hasher(self):
        """Create a PasswordHasher instance."""
        return PasswordHasher()

    def test_hash_returns_bcrypt_hash(self, hasher):
        """Test that hash() returns a bcrypt hash."""
        password = "test_password_123"
        hashed = hasher.hash(password)

        assert hashed != password
        assert hashed.startswith("$2b$")

    def test_hash_produces_different_hashes(self, hasher):
        """Test that hashing the same password twice produces different hashes (due to salt)."""
        password = "test_password"
        hash1 = hasher.hash(password)
        hash2 = hasher.hash(password)

        assert hash1 != hash2

    def test_verify_correct_password(self, hasher):
        """Test that verify() returns True for correct password."""
        password = "correct_password"
        hashed = hasher.hash(password)

        assert hasher.verify(password, hashed) is True

    def test_verify_wrong_password(self, hasher):
        """Test that verify() returns False for wrong password."""
        password = "correct_password"
        hashed = hasher.hash(password)

        assert hasher.verify("wrong_password", hashed) is False

    def test_verify_empty_password(self, hasher):
        """Test verify with empty password."""
        hashed = hasher.hash("some_password")

        assert hasher.verify("", hashed) is False

    def test_hash_empty_password(self, hasher):
        """Test that hashing an empty password works."""
        hashed = hasher.hash("")

        assert hashed.startswith("$2b$")
        assert hasher.verify("", hashed) is True

    def test_hash_special_characters(self, hasher):
        """Test hashing passwords with special characters."""
        password = "p@$$w0rd!#%^&*()_+-=[]{}|;':\",./<>?"
        hashed = hasher.hash(password)

        assert hasher.verify(password, hashed) is True

    def test_hash_unicode_password(self, hasher):
        """Test hashing passwords with unicode characters."""
        password = "пароль密码كلمة السر"
        hashed = hasher.hash(password)

        assert hasher.verify(password, hashed) is True

    def test_hash_long_password(self, hasher):
        """Test hashing very long passwords."""
        password = "a" * 1000
        hashed = hasher.hash(password)

        # bcrypt truncates at 72 bytes, but verify should still work
        assert hasher.verify(password, hashed) is True

    def test_verify_malformed_hash(self, hasher):
        """Test that verify() rejects a non-bcrypt hash instead of raising."""
        assert hasher.verify("any_password", "not-a-bcrypt-hash") is False

    def test_verify_hash_from_stored_bcrypt_hash(self, hasher):
        """Test that verify() accepts a pre-existing $2b$ hash from the database."""
        # Generated by bcrypt for the password "correct_password".
        stored = "$2b$12$GJekjqrJLo1FGWZZCKVZB.xuxGCQpri7RQg9iteVy2D5kvfG6HT3y"

        assert hasher.verify("correct_password", stored) is True
        assert hasher.verify("wrong_password", stored) is False


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
