"""On-disk layout of ComfyUI-quantised checkpoints, as a declared table.

Everything here was transcribed from published checkpoints — safetensors headers
and descriptor blobs read out of files, plus the int8 facts established by a
survey of released int8/ConvRot artefacts. Nothing is generated by calling
``vendor.gpl.comfyui.ops``: this table is the specification the loader is tested
against, and building it from the code under test only proves that code agrees
with itself.

fp8/nvfp4 entries were read from files in this machine's library:

    museByStableYogi_v20TurboINT8        fp8, per-layer blob, no input_scale
    qwen_image_edit_2511_fp8mixed        fp8 + input_scale + bf16 bias
    qwen_3_8b_fp8mixed                   fp8 layers + bare-"nvfp4" layers
    Gemma3-12B-NVFP4-Sikaworld-HF        nvfp4 with group_size/orig_shape
    UMT5_XXL_NVFP4                       nvfp4, fp16 originals

Note the trap in the first name: the only file in this library whose FILENAME
says INT8 carries ``{"format": "float8_e4m3fn"}`` and is an fp8 file. No int8
checkpoint is available here, so the int8 layouts below are SYNTHESISED from the
documented format — real-weight verification stays a maintainer gate.
"""

from __future__ import annotations

import json

import torch

# --- descriptor encoding (read from files) -----------------------------------
#
# The per-layer descriptor is UTF-8 JSON in a rank-1 U8 tensor sized to the JSON
# byte count. `format` is the only field every observed descriptor carries; the
# rest are format-specific, and unknown fields are routine — a reader must ignore
# what it does not recognise rather than reject the layer.
CONFIRMED_DESCRIPTORS: list[dict] = [
    {"format": "float8_e4m3fn"},
    {"format": "float8_e4m3fn", "full_precision_matrix_mult": False},
    {"format": "float8_e4m3fn", "full_precision_matrix_mult": True},
    {"format": "nvfp4"},
    {
        "format": "nvfp4",
        "group_size": 16,
        "orig_dtype": "torch.bfloat16",
        "orig_shape": [3840, 15360],
    },
]

CONFIRMED_FP8_LAYER: dict[str, tuple[torch.dtype, tuple]] = {
    "weight": (torch.float8_e4m3fn, ("out", "in")),
    "weight_scale": (torch.float32, ()),
    "comfy_quant": (torch.uint8, ("json_bytes",)),
}

# --- int8_tensorwise: keys ---------------------------------------------------
#
# One code per byte, so the stored weight shape IS the layer's true shape (unlike
# nvfp4, which packs two 4-bit codes per byte and stores a half-width weight).
# There is no zero point, no `input_scale` and no `weight_scale_2` — a reader
# that expects any of those is reading the wrong format.
INT8_FORBIDDEN_KEYS: tuple[str, ...] = (
    "input_scale", "scale_input", "weight_scale_2", "zero_point",
)

# ConvRot: per-output-channel scale. Every released artefact uses [out, 1].
INT8_CONVROT_LAYER: dict[str, tuple[torch.dtype, tuple]] = {
    "weight": (torch.int8, ("out", "in")),
    "weight_scale": (torch.float32, ("out", 1)),
    "comfy_quant": (torch.uint8, ("json_bytes",)),
}

# Plain tensorwise: one scale for the whole tensor, hence the format name. The
# scale's RANK is the on-the-wire signal distinguishing the two: `scale.dim() > 0`
# means per-channel.
INT8_PLAIN_LAYER: dict[str, tuple[torch.dtype, tuple]] = {
    "weight": (torch.int8, ("out", "in")),
    "weight_scale": (torch.float32, ()),
    "comfy_quant": (torch.uint8, ("json_bytes",)),
}

# --- int8_tensorwise: descriptors --------------------------------------------
#
# Top-level keys, spelled exactly `format` / `convrot` / `convrot_groupsize`
# (one word). Released files differ only in JSON serialisation and in whether
# they state the group size at all, which shows up as the byte length of the
# blob. All four lengths below are lengths seen in the wild; the canonical
# rotated form is 72 bytes.
INT8_PLAIN_DESCRIPTOR: dict = {"format": "int8_tensorwise"}

CONVROT_DEFAULT_GROUPSIZE = 256

# (byte length in the wild, description, json.dumps kwargs, extra build options)
CONVROT_WILD_FORMS: list[tuple[int, str, dict, dict]] = [
    (72, "canonical: default separators, group size stated", {}, {}),
    (67, "compact separators, group size stated", {"separators": (",", ":")}, {}),
    (43, "compact separators, NO group size stated",
     {"separators": (",", ":")}, {"drop_groupsize": True}),
    (89, "default separators + a stray per_row flag", {}, {"per_row": True}),
]

# int8 symmetric range: signed codes, no zero point. -128 is unused so +/- share
# one scale.
INT8_CODE_MAX = 127

# Sizes the Hadamard's symmetry/involution is asserted at.
HADAMARD_SIZES: tuple[int, ...] = (4, 16, 256, 1024)


def convrot_descriptor(
    groupsize: int,
    *,
    nested: bool = False,
    per_row: bool = False,
    drop_groupsize: bool = False,
) -> dict:
    """An int8_tensorwise ConvRot descriptor.

    ``nested`` puts the ConvRot entries under a ``params`` dict — accepted by
    ComfyUI's loader but used by no released file. ``drop_groupsize`` is the
    real-world variant that states ``convrot`` without a group size.
    """
    entries: dict = {"convrot": True}
    if not drop_groupsize:
        entries["convrot_groupsize"] = groupsize
    if nested:
        conf: dict = {"format": "int8_tensorwise", "params": entries}
    else:
        conf = {"format": "int8_tensorwise", **entries}
    if per_row:
        conf["per_row"] = True
    return conf


def descriptor_blob(conf: dict, **dumps_kwargs) -> torch.Tensor:
    """The U8 JSON tensor a checkpoint stores for one layer's ``comfy_quant``."""
    raw = json.dumps(conf, **dumps_kwargs).encode("utf-8")
    return torch.tensor(list(raw), dtype=torch.uint8)


def convrot_wild_blob(groupsize: int, form: tuple[int, str, dict, dict]) -> torch.Tensor:
    """Build one real-world descriptor variant from ``CONVROT_WILD_FORMS``."""
    _, _, dumps_kwargs, extras = form
    conf = convrot_descriptor(
        groupsize,
        per_row=bool(extras.get("per_row")),
        drop_groupsize=bool(extras.get("drop_groupsize")),
    )
    return descriptor_blob(conf, **dumps_kwargs)


# --- file-level header -------------------------------------------------------
#
# `__metadata__["_quantization_metadata"]` is a JSON *string* holding
# `{"format_version": "1.0", "layers": {...}}`, whose layer keys omit the
# trailing `.weight`. Only `layers` is ever read. Two of four published int8
# checkpoints carry it; two rely purely on the per-layer descriptors, and both
# shapes are valid.
def quantization_metadata_header(layer_names: list[str], descriptor: dict) -> dict[str, str]:
    """A file-level ``__metadata__`` block describing ``layer_names``."""
    payload = {
        "format_version": "1.0",
        "layers": {name: descriptor for name in layer_names},
    }
    return {"_quantization_metadata": json.dumps(payload)}


def resolve_shape(shape: tuple, *, out_f: int, in_f: int, json_bytes: int = 0) -> tuple[int, ...]:
    """Turn a declared shape tuple's placeholders into concrete dimensions."""
    dims: list[int] = []
    for s in shape:
        if s == "out":
            dims.append(out_f)
        elif s == "in":
            dims.append(in_f)
        elif s == "json_bytes":
            dims.append(json_bytes)
        else:
            dims.append(int(s))
    return tuple(dims)


# --- independent reference quantiser ----------------------------------------
#
# Written from the format description (regular H4, Kronecker-powered, normalised
# by 1/sqrt(size), applied per in_features block), NOT by calling the loader — so
# a mistake there fails a test instead of both sides agreeing on it.


def reference_hadamard(size: int) -> torch.Tensor:
    h4 = torch.tensor(
        [[1, 1, 1, -1], [1, 1, -1, 1], [1, -1, 1, 1], [-1, 1, 1, 1]],
        dtype=torch.float32,
    )
    h = h4
    n = 4
    while n < size:
        h = torch.kron(h, h4)
        n *= 4
    return h / (size ** 0.5)


def reference_rotate(w: torch.Tensor, h: torch.Tensor, group_size: int) -> torch.Tensor:
    out_f, in_f = w.shape
    n_groups = in_f // group_size
    return torch.matmul(w.reshape(out_f, n_groups, group_size), h.T).reshape(out_f, in_f)


def reference_quantize_convrot(w: torch.Tensor, group_size: int):
    """Offline rotate, then per-output-channel int8 quantise. Returns ``(codes, scale)``."""
    rotated = reference_rotate(w.float(), reference_hadamard(group_size), group_size)
    scale = (rotated.abs().amax(dim=-1, keepdim=True) / INT8_CODE_MAX).clamp(min=1e-8)
    codes = (rotated / scale).round().clamp(-INT8_CODE_MAX, INT8_CODE_MAX).to(torch.int8)
    return codes, scale


def reference_quantize_plain(w: torch.Tensor):
    """Tensor-wide int8 quantise. Returns ``(codes, scale)`` with a rank-0 scale."""
    scale = (w.float().abs().amax() / INT8_CODE_MAX).clamp(min=1e-8).reshape(())
    codes = (w.float() / scale).round().clamp(-INT8_CODE_MAX, INT8_CODE_MAX).to(torch.int8)
    return codes, scale


def int8_state_dict(
    out_f: int,
    in_f: int,
    *,
    prefix: str = "proj.",
    convrot: bool = False,
    groupsize: int = CONVROT_DEFAULT_GROUPSIZE,
    descriptor: dict | None = None,
    blob: torch.Tensor | None = None,
    bias_dtype: torch.dtype | None = None,
    seed: int = 6,
):
    """One int8_tensorwise layer laid out per the tables above.

    Returns ``(state_dict, original_weight, codes, scale)``. ``original_weight``
    is the pre-quantisation float weight — the ground truth a correct dequant must
    recover, rotated or not.
    """
    torch.manual_seed(seed)
    w = torch.randn(out_f, in_f) * 0.5
    if convrot:
        codes, scale = reference_quantize_convrot(w, groupsize)
        if descriptor is None:
            descriptor = convrot_descriptor(groupsize)
    else:
        codes, scale = reference_quantize_plain(w)
        if descriptor is None:
            descriptor = dict(INT8_PLAIN_DESCRIPTOR)
    sd = {
        prefix + "weight": codes,
        prefix + "weight_scale": scale,
        prefix + "comfy_quant": blob if blob is not None else descriptor_blob(descriptor),
    }
    if bias_dtype is not None:
        sd[prefix + "bias"] = torch.randn(out_f, dtype=bias_dtype) * 0.1
    return sd, w, codes, scale
